### ISSUE TITLE
Uncaught TypeError: Cannot read property 'project' of null

### ISSUE THREAD

**Issue by yatiac** [maximeh/leaflet.bouncemarker#30]
Sometimes this error is logged when marker.bounce is called.

Debugging a little bit I found that this happens when self._map is null for some reason.

It might be worth checking if map is different from undefined.

It happens @ requestAnimFrame.

**Comment by maximeh** [comment]
Hi there,

First; thanks for reporting your issue and sorry that it took me so long to look at it.

I was able to reproduce (at least I think) by doing this:
https://jsfiddle.net/eft760am/

But as you see; if you don't add the Marker to a map; you cannot call bounce; because it needs the marker ```onAdd()``` to be executed before you can call ```bounce()``` as many values are not filled in the object before that.

So there's nothing that I can do here.

Do not hesitate to re-open this issue if you find that I misunderstood something.
