### ISSUE TITLE
leaflet.js:5 Uncaught TypeError: Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by ProWilbert** [maximeh/leaflet.bouncemarker#32]
In combination with leaflet version 1.3.0 and leaflet markercluster, error 'cannot read property 'parentNode' of undefined'.

**Comment by ProWilbert** [comment]
Hi Maxime,

See https://jsfiddle.net/mr2s8a0L/
Browser: Chrome, see console for the error:
[cid:image001.png@01D3FABC.9B70C150]

Thanks a lot, by the way, the bounce plugin looks great, good work!

Cheers,
Wilbert

Van: Maxime Hadjinlian [mailto:notifications@github.com]
Verzonden: zaterdag 2 juni 2018 21:23
Aan: maximeh/leaflet.bouncemarker <leaflet.bouncemarker@noreply.github.com>
CC: Wilbert Verplanke <wilbert@prodev.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [maximeh/leaflet.bouncemarker] leaflet.js:5 Uncaught TypeError: Cannot read property 'parentNode' of undefined (#32)


Do you have any code to reproduce this issue ? That would help me a lot.

**Comment by maximeh** [comment]
Hey

I tried to have a look; it seems it's going to be hard to make theses two plugins compatibles. MarkerCluster redefines a lot of the Marker object.

I'll try but I can't promise anything, if you have some ideas; they are welcome :)

**Comment by maximeh** [comment]
@ProWilbert I looked again at your problem and I am really scratching my head here. It seams that there's an issue because I have a '_map' object assigned. If i change the name of this variable, I don't have an error anymore but it doesn't seem to work anyway.
I have looked a little bit at the code of MarkerClusters and can't really figure out why it doesn't seem  to work.
