### ISSUE TITLE
how to draggable

### ISSUE THREAD

**Issue by 2qq2qq** [maximeh/leaflet.bouncemarker#34]
no draggable？

**Comment by maximeh** [comment]
What do you mean ? Do you have code ? What are you trying to achieve ? 
When reporting an issue, it's nice to type more than 5 words.

**Comment by thomasbrueggemann** [comment]
I have noticed, that markers are not draggable while bouncing. I guess this is what @2qq2qq tried to express. 
Was that an intentional design decision, @maximeh ?

**Comment by thomasbrueggemann** [comment]
I was just able the remedy the issue by stopping the bouncing on marker drag-start and resuming to bounce on dragend.

**Comment by maximeh** [comment]
Hey there !

Sorry for the late reply.

I don't remember if it was intentional or not, but I would be curious to see a use case where you want to drag a point *while* it's bouncing, seems a bit odd, even to grab the point seems a bit like a game :).

@thomasbrueggemann thanks for the tips on how to realize the operation !
