### ISSUE TITLE
Typescript complain over types

### ISSUE THREAD

**Issue by technbuzz** [maximeh/leaflet.bouncemarker#35]
Any types available for this plugin?  as I am getting following error
![image](https://user-images.githubusercontent.com/1523391/84877317-68071180-b099-11ea-9720-40887c9e5070.png)

**Comment by maximeh** [comment]
Hey there,
Did you add bouncemarker.js to your file? The plugin will add the option to the marker class.
I don't use any IDE (I use vim); so I'm not sure what's going on there but it seems like a setup issue?

**Comment by technbuzz** [comment]
The plugins works fine, only that I don't get any intellisense in VSCode.

By the way, I can't imagine how do you work without the intellisense, do you always look the documentation or you add the api to your muscle memory?

**Comment by maximeh** [comment]
Yeah I basically have the browser on one desktop, and another with a terminal full screen and work in there. It's small enough that I'm pretty happy that way (I do use IDE for other bigger project, but that's small enough to work like that).
Did you figure it out in the end? Could I do something to help there?

**Comment by bhdzllr** [comment]
Since @technbuzz uses TypeScript, the problem can be bypassed with the use of "as any" after the marker options. Of course a better solution so you don't loose type hints for all marker options would be to use type definitions.

This can be done with a file named "leaflet.bouncemarker.d.ts" and the following content. This works for me, I don't know if it is best practices or the common way to add options to an existing interface so I don't know if it is a good idea to include this in the repository:

```TypeScript
import * as L from 'leaflet';

declare module 'leaflet' {

	export interface MarkerOptions extends InteractiveLayerOptions {

		bounceOnAdd?: boolean;

		bounceOnAddOptions?: {
			duration: number,
			height: number,
			loop: number
		};

		bounceOnAddCallback?: Function;

	}

}

```

**Comment by maximeh** [comment]
From what I'm reading it seems to make sense to add that file to the repo so it's there for whomever wanna use it, care to open a PR?

**Comment by bhdzllr** [comment]
@maximeh Ok, I will open a pull request.

**Comment by programadorsalazarburgos** [comment]
what is solutions ?

**Comment by maximeh** [comment]
I don't speak Spanish but you can use the latests release if you want to have that fixed:
https://github.com/maximeh/leaflet.bouncemarker/releases/tag/v1.2.1
